# Generated by Django 3.2.9 on 2021-11-10 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('instructor', models.CharField(max_length=300)),
                ('courseimg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
